2022-03-02T18:31:35.5046630+05:30 [ERR] 
Class name:Program, Method name: Some Inner Method,
Business functionality: A program to test custom exception handler,
Stack Trace:   at CustomExceptionHandlerTester.Program.Main(String[] args) in C:\Users\dipak.dhande\source\repos\CustomExceptionHandler\CustomExceptionHandlerTester\Program.cs:line 15,
Inner exception: 
--------------------------------------
2022-03-02T18:31:35.5388009+05:30 [ERR] 
Class name:Program, Method name: Main,
Business functionality: A program to test custom exception handler,
Stack Trace:   at CustomExceptionHandlerTester.Program.Main(String[] args) in C:\Users\dipak.dhande\source\repos\CustomExceptionHandler\CustomExceptionHandlerTester\Program.cs:line 23,
Inner exception: 
--------------------------------------
2022-03-02T18:32:25.2177760+05:30 [ERR] 
Class name:Program, Method name: Some Inner Method,
Business functionality: A program to test custom exception handler,
Stack Trace:   at CustomExceptionHandlerTester.Program.Main(String[] args) in C:\Users\dipak.dhande\source\repos\CustomExceptionHandler\CustomExceptionHandlerTester\Program.cs:line 15,
Inner exception: 
--------------------------------------
2022-03-02T18:32:25.2767273+05:30 [ERR] 
Class name:Program, Method name: Main,
Business functionality: A program to test custom exception handler,
Stack Trace:   at CustomExceptionHandlerTester.Program.Main(String[] args) in C:\Users\dipak.dhande\source\repos\CustomExceptionHandler\CustomExceptionHandlerTester\Program.cs:line 23,
Inner exception: 
--------------------------------------
2022-03-02T18:32:49.2622113+05:30 [ERR] 
Class name:Program, Method name: Some Inner Method,
Business functionality: A program to test custom exception handler,
Stack Trace:   at CustomExceptionHandlerTester.Program.Main(String[] args) in C:\Users\dipak.dhande\source\repos\CustomExceptionHandler\CustomExceptionHandlerTester\Program.cs:line 15,
Inner exception: 
--------------------------------------
2022-03-02T18:32:49.3206701+05:30 [ERR] 
Class name:Program, Method name: Main,
Business functionality: A program to test custom exception handler,
Stack Trace:   at CustomExceptionHandlerTester.Program.Main(String[] args) in C:\Users\dipak.dhande\source\repos\CustomExceptionHandler\CustomExceptionHandlerTester\Program.cs:line 23,
Inner exception: 
--------------------------------------
2022-03-02T18:35:37.2889890+05:30 [ERR] 
Class name:Program, Method name: Some Inner Method,
Business functionality: A program to test custom exception handler,
Stack Trace:   at CustomExceptionHandlerTester.Program.Main(String[] args) in C:\Users\dipak.dhande\source\repos\CustomExceptionHandler\CustomExceptionHandlerTester\Program.cs:line 15,
Inner exception: 
--------------------------------------
2022-03-02T18:35:42.2360434+05:30 [ERR] 
Class name:Program, Method name: Main,
Business functionality: A program to test custom exception handler,
Stack Trace:   at CustomExceptionHandlerTester.Program.Main(String[] args) in C:\Users\dipak.dhande\source\repos\CustomExceptionHandler\CustomExceptionHandlerTester\Program.cs:line 23,
Inner exception: 
--------------------------------------
